// AUTOGENERATED FILE: easyjson marshaller/unmarshallers.

package openrtb

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson326edDecodeGithubComMxmCherryOpenrtb(in *jlexer.Lexer, out *BidResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "seatbid":
			if in.IsNull() {
				in.Skip()
				out.SeatBid = nil
			} else {
				in.Delim('[')
				if !in.IsDelim(']') {
					out.SeatBid = make([]SeatBid, 0, 1)
				} else {
					out.SeatBid = []SeatBid{}
				}
				for !in.IsDelim(']') {
					var v1 SeatBid
					easyjson326edDecodeGithubComMxmCherryOpenrtb1(in, &v1)
					out.SeatBid = append(out.SeatBid, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "bidid":
			out.BidID = string(in.String())
		case "cur":
			out.Cur = string(in.String())
		case "customdata":
			out.CustomData = string(in.String())
		case "nbr":
			out.NBR = int8(in.Int8())
		case "ext":
			out.Ext = in.Interface()
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson326edEncodeGithubComMxmCherryOpenrtb(out *jwriter.Writer, in BidResponse) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"id\":")
	out.String(string(in.ID))
	if len(in.SeatBid) != 0 {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"seatbid\":")
		if in.SeatBid == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.SeatBid {
				if v2 > 0 {
					out.RawByte(',')
				}
				easyjson326edEncodeGithubComMxmCherryOpenrtb1(out, v3)
			}
			out.RawByte(']')
		}
	}
	if in.BidID != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"bidid\":")
		out.String(string(in.BidID))
	}
	if in.Cur != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"cur\":")
		out.String(string(in.Cur))
	}
	if in.CustomData != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"customdata\":")
		out.String(string(in.CustomData))
	}
	if in.NBR != 0 {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"nbr\":")
		out.Int8(int8(in.NBR))
	}
	if in.Ext != nil {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"ext\":")
		if m, ok := in.Ext.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Ext.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Ext))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BidResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson326edEncodeGithubComMxmCherryOpenrtb(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BidResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson326edEncodeGithubComMxmCherryOpenrtb(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BidResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson326edDecodeGithubComMxmCherryOpenrtb(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BidResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson326edDecodeGithubComMxmCherryOpenrtb(l, v)
}
func easyjson326edDecodeGithubComMxmCherryOpenrtb1(in *jlexer.Lexer, out *SeatBid) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "bid":
			if in.IsNull() {
				in.Skip()
				out.Bid = nil
			} else {
				in.Delim('[')
				if !in.IsDelim(']') {
					out.Bid = make([]Bid, 0, 1)
				} else {
					out.Bid = []Bid{}
				}
				for !in.IsDelim(']') {
					var v4 Bid
					easyjson326edDecodeGithubComMxmCherryOpenrtb2(in, &v4)
					out.Bid = append(out.Bid, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "seat":
			out.Seat = string(in.String())
		case "group":
			out.Group = int8(in.Int8())
		case "ext":
			out.Ext = in.Interface()
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson326edEncodeGithubComMxmCherryOpenrtb1(out *jwriter.Writer, in SeatBid) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"bid\":")
	if in.Bid == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v5, v6 := range in.Bid {
			if v5 > 0 {
				out.RawByte(',')
			}
			easyjson326edEncodeGithubComMxmCherryOpenrtb2(out, v6)
		}
		out.RawByte(']')
	}
	if in.Seat != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"seat\":")
		out.String(string(in.Seat))
	}
	if in.Group != 0 {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"group\":")
		out.Int8(int8(in.Group))
	}
	if in.Ext != nil {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"ext\":")
		if m, ok := in.Ext.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Ext.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Ext))
		}
	}
	out.RawByte('}')
}
func easyjson326edDecodeGithubComMxmCherryOpenrtb2(in *jlexer.Lexer, out *Bid) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "impid":
			out.ImpID = string(in.String())
		case "price":
			out.Price = float64(in.Float64())
		case "adid":
			out.AdID = string(in.String())
		case "nurl":
			out.NURL = string(in.String())
		case "adm":
			out.AdM = string(in.String())
		case "adomain":
			if in.IsNull() {
				in.Skip()
				out.ADomain = nil
			} else {
				in.Delim('[')
				if !in.IsDelim(']') {
					out.ADomain = make([]string, 0, 4)
				} else {
					out.ADomain = []string{}
				}
				for !in.IsDelim(']') {
					var v7 string
					v7 = string(in.String())
					out.ADomain = append(out.ADomain, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "bundle":
			out.Bundle = string(in.String())
		case "iurl":
			out.IURL = string(in.String())
		case "cid":
			out.CID = string(in.String())
		case "crid":
			out.CrID = string(in.String())
		case "cat":
			if in.IsNull() {
				in.Skip()
				out.Cat = nil
			} else {
				in.Delim('[')
				if !in.IsDelim(']') {
					out.Cat = make([]string, 0, 4)
				} else {
					out.Cat = []string{}
				}
				for !in.IsDelim(']') {
					var v8 string
					v8 = string(in.String())
					out.Cat = append(out.Cat, v8)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "attr":
			if in.IsNull() {
				in.Skip()
				out.Attr = nil
			} else {
				in.Delim('[')
				if !in.IsDelim(']') {
					out.Attr = make([]int8, 0, 64)
				} else {
					out.Attr = []int8{}
				}
				for !in.IsDelim(']') {
					var v9 int8
					v9 = int8(in.Int8())
					out.Attr = append(out.Attr, v9)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "dealid":
			out.DealID = string(in.String())
		case "h":
			out.H = uint64(in.Uint64())
		case "w":
			out.W = uint64(in.Uint64())
		case "ext":
			out.Ext = in.Interface()
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson326edEncodeGithubComMxmCherryOpenrtb2(out *jwriter.Writer, in Bid) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"id\":")
	out.String(string(in.ID))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"impid\":")
	out.String(string(in.ImpID))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"price\":")
	out.Float64(float64(in.Price))
	if in.AdID != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"adid\":")
		out.String(string(in.AdID))
	}
	if in.NURL != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"nurl\":")
		out.String(string(in.NURL))
	}
	if in.AdM != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"adm\":")
		out.String(string(in.AdM))
	}
	if len(in.ADomain) != 0 {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"adomain\":")
		if in.ADomain == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v10, v11 := range in.ADomain {
				if v10 > 0 {
					out.RawByte(',')
				}
				out.String(string(v11))
			}
			out.RawByte(']')
		}
	}
	if in.Bundle != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"bundle\":")
		out.String(string(in.Bundle))
	}
	if in.IURL != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"iurl\":")
		out.String(string(in.IURL))
	}
	if in.CID != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"cid\":")
		out.String(string(in.CID))
	}
	if in.CrID != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"crid\":")
		out.String(string(in.CrID))
	}
	if len(in.Cat) != 0 {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"cat\":")
		if in.Cat == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v12, v13 := range in.Cat {
				if v12 > 0 {
					out.RawByte(',')
				}
				out.String(string(v13))
			}
			out.RawByte(']')
		}
	}
	if len(in.Attr) != 0 {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"attr\":")
		if in.Attr == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v14, v15 := range in.Attr {
				if v14 > 0 {
					out.RawByte(',')
				}
				out.Int8(int8(v15))
			}
			out.RawByte(']')
		}
	}
	if in.DealID != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"dealid\":")
		out.String(string(in.DealID))
	}
	if in.H != 0 {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"h\":")
		out.Uint64(uint64(in.H))
	}
	if in.W != 0 {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"w\":")
		out.Uint64(uint64(in.W))
	}
	if in.Ext != nil {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"ext\":")
		if m, ok := in.Ext.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Ext.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Ext))
		}
	}
	out.RawByte('}')
}
